name: Continuous Integration

on:
  push:
    branches: ['**']
    tags: [v*]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MILL_JVM_OPTS_PATH: '.mill-jvm-opts-ci'

jobs:
  check-format:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ '2.13.10' ]
        java: [ '17' ]
        platform: [ 'jvm' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Check formatting
        run:
          ./mill -i '__.${{ matrix.platform }}[${{ matrix.scala }}].checkFormat'

  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ '2.13.10', '3.2.2' ]
        java: [ '8', '19' ]
        platform: [ 'jvm', 'js' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Test
        run:
          ./mill -i all '__.${{ matrix.platform }}[${{ matrix.scala }}].compile' '__.${{ matrix.platform }}[${{ matrix.scala }}].test'
