name: Sourcegraph
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scip:
    runs-on: ubuntu-latest
    name: "Upload SCIP"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: 'temurin:11'
          apps: scip-java
      - uses: jodersky/setup-mill@8b45755d42c3a3f063af57f1bb40c2c6737d0c86
        with:
          mill-version: 0.10.11
      - name: Generate SCIP File
        run: scip-java index --build-tool=mill

      - name: Install src
        run: yarn global add @sourcegraph/src

      - name: Upload SCIP file
        run: src code-intel upload -github-token $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
